artifact_location: /home/zain/work/learning/deep_learning/vision/MaskDetection/Notebook/runs/mlflow/0
creation_time: 1753820337323
experiment_id: '0'
last_update_time: 1753820337323
lifecycle_stage: active
name: Default
