artifact_location: /home/zain/work/learning/deep_learning/vision/MaskDetection/Notebook/runs/mlflow/858483303677411717
creation_time: 1753820337330
experiment_id: '858483303677411717'
last_update_time: 1753820337330
lifecycle_stage: active
name: /Shared/Ultralytics
